# Generated by Django 3.0.7 on 2020-06-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(max_length=1000, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(max_length=50, verbose_name='Название отзыва'),
        ),
    ]
