# Generated by Django 3.0.7 on 2020-06-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200624_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
