# Generated by Django 3.0.7 on 2020-06-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказа'},
        ),
    ]
